name: Auto-update clients

on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: true
      - name: Compile EaglercraftX 1.8
        if: success() || failure()
        run: |
          git clone https://git.eaglercraft.rip/eaglercraft/eaglercraft-1.8-workspace.git ${{ runner.temp }}/eaglerx
          rm -rf \
            ./src/game/web/main/1.8.8/lang/ \
            ./src/game/web/main/1.8.8/assets.epk \
            ./src/game/web/main/1.8.8/classes.js \
            ./src/game/web/main/1.8.8/classes.js.map \
            ./src/game/offline/main/EaglercraftX_1.8.html \
            ${{runner.temp}}/eaglerx/javascript/assets.epk \
            ${{runner.temp}}/eaglerx/javascript/classes.js \
          cd ${{runner.temp}}/eaglerx/
          chmod +x ./gradlew
          java -jar "desktopRuntime/CompileEPK.jar" "desktopRuntime/resources" "javascript/assets.epk"
          ./gradlew generateJavascript
          wget -O ${{ github.workspace }}/src/game/offline/main/EaglercraftX_1.8.html https://git.eaglercraft.rip/eaglercraft/eaglercraft-builds/raw/branch/main/EaglercraftX_1.8_Offline_Signed_Client.html
          cd ${{ github.workspace }}
          cp -r ${{ runner.temp }}/eaglerx/javascript/lang/ ./src/game/web/main/1.8.8/lang/
          cp ${{ runner.temp }}/eaglerx/javascript/assets.epk ./src/game/web/main/1.8.8/assets.epk
          cp ${{ runner.temp }}/eaglerx/javascript/classes.js ./src/game/web/main/1.8.8/classes.js
      # FREEZE AT V0.6.1 UNTIL FURTHER NOTICE
      #- name: Compile EaglercraftL 1.9
      #  if: success() || failure()
      #  run: |
      #    git clone https://git.zelz.net/Eagler-Lambda/hoosiertransfer-mod.git ${{ runner.temp }}/eaglerl
      #    rm -rf \
      #      ./src/game/web/main/1.9.4/lang/ \
      #      ./src/game/web/main/1.9.4/assets.epk \
      #      ./src/game/web/main/1.9.4/classes.js \
      #      ./src/game/web/main/1.9.4/classes.js.map \
      #      ./src/game/offline/main/EaglercraftL_1.9.html \
      #      ${{runner.temp}}/eaglerl/javascript/assets.epk \
      #      ${{runner.temp}}/eaglerl/javascript/classes.js \
      #    cd ${{runner.temp}}/eaglerl/
      #    chmod +x ./gradlew
      #    java -jar "resources/CompileEPK.jar" "resources/resources" "javascript/assets.epk"
      #    ./gradlew generateJavascript
      #    wget -O ${{ github.workspace }}/src/game/offline/main/EaglercraftL_1.9.html https://git.zelz.net/Eagler-Lambda/hoosiertransfer-mod/releases/download/latest/EaglercraftL_1.9_Offline_Signed_Client.html
      #    cd ${{ github.workspace }}
      #    cp -r ${{ runner.temp }}/eaglerl/javascript/lang/ ./src/game/web/main/1.9.4/lang/
      #    cp ${{ runner.temp }}/eaglerl/javascript/assets.epk ./src/game/web/main/1.9.4/assets.epk
      #    cp ${{ runner.temp }}/eaglerl/javascript/classes.js ./src/game/web/main/1.9.4/classes.js
      - name: Compile Shadow Client
        if: success() || failure()
        run: |
          git clone https://github.com/PeytonPlayz595/Shadow-4.0.git ${{ runner.temp }}/shadow
          rm -rf \
            ./src/game/web/clients/shadow/lang/ \
            ./src/game/web/clients/shadow/assets.epk \
            ./src/game/web/clients/shadow/classes.js \
            ./src/game/web/clients/shadow/classes.js.map \
            ./src/game/offline/clients/Shadow_Client.html \
            ${{runner.temp}}/shadow/javascript/assets.epk \
            ${{runner.temp}}/shadow/javascript/classes.js \
          cd ${{runner.temp}}/shadow/
          chmod +x ./gradlew
          java -jar "desktopRuntime/CompileEPK.jar" "desktopRuntime/resources" "javascript/assets.epk"
          ./gradlew generateJavascript
          java -cp "desktopRuntime/MakeOfflineDownload.jar:desktopRuntime/CompileEPK.jar" net.lax1dude.eaglercraft.v1_8.buildtools.workspace.MakeOfflineDownload "javascript/OfflineDownloadTemplate.txt" "javascript/classes.js" "javascript/assets.epk" "/dev/null" "javascript/Shadow_Client_International.html" "javascript/lang"
          cd ${{ github.workspace }}
          cp -r ${{ runner.temp }}/shadow/javascript/lang/ ./src/game/web/clients/shadow/lang/
          cp ${{ runner.temp }}/shadow/javascript/assets.epk ./src/game/web/clients/shadow/assets.epk
          cp ${{ runner.temp }}/shadow/javascript/classes.js ./src/game/web/clients/shadow/classes.js
          cp ${{ runner.temp }}/shadow/javascript/Shadow_Client_International.html ./src/game/offline/clients/Shadow_Client.html
      - name: Commit and push changes
        id: git-auto-commit-action
        if: success() || failure()
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'github-actions: auto-update clients'
          commit_author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
