name: Auto-update clients

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.ref == 'refs/heads/main' }}
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Compile EaglercraftX 1.8
        run: |
          rm ${{ github.workspace }}/src/game/main/1.8.8/lang/*
          git clone https://git.eaglercraft.rip/eaglercraft/eaglercraft-1.8-workspace.git ${{ runner.temp }}/eaglerx
          cd ${{ runner.temp }}/eaglerx
          bash ./CompileEPK.sh
          bash ./CompileJS.sh
          cp --no-preserve=mode ${{ runner.temp }}/eaglerx/javascript/assets.epk ${{ github.workspace }}/src/game/main/1.8.8/assets.epk
          cp --no-preserve=mode ${{ runner.temp }}/eaglerx/javascript/classes.js ${{ github.workspace }}/src/game/main/1.8.8/classes.js
          cp --no-preserve=mode ${{ runner.temp }}/eaglerx/javascript/lang/* ${{ github.workspace }}/src/game/main/1.8.8/lang
          wget -O ${{ github.workspace }}/src/game/main/1.8.8/offline.html https://git.eaglercraft.rip/eaglercraft/eaglercraft-builds/raw/branch/main/EaglercraftX_1.8_Offline_Signed_Client.html
      - name: Commit and push changes
        id: git-auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'github-actions: auto-update clients'
          commit_author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
